### ISSUE TITLE
please update Beacon SDK / Taquito

### ISSUE THREAD

**Issue by djangobits** [bender-labs/wrap-dapp#5]
Hey there,
I am from Papers AG, who maintains the Beacon SDK. We recently discovered a vulnerability in the Beacon SDK, more info here:

https://docs.walletbeacon.io/post-mortem-2

Also see:
https://twitter.com/AirGap_it/status/1514272606794432519
and
https://twitter.com/TezosTaquito/status/1514308832071020544

Please upgrade to the latest version of Beacon (2.3.13) or Taquito (12.0.3).
best regards!

**Comment by couillardcharles** [comment]
Hi @djangobits,

Thank you for the notification!

Fixed here: https://github.com/bender-labs/wrap-dapps/commit/0f5a45051ada927cf947151c9ca7ac6768c0bd01
